// Script to generate AoW compatibility CSV from Google Sheets data

import fs from 'fs';
import path from 'path';

// Weapon data: [class, name, id] - Complete list from WeaponData sheet
const weaponsData = [
  ["Dagger","Dagger","1000000"],
  ["Dagger","Parrying Dagger","1020000"],
  ["Dagger","Miséricorde","1030000"],
  ["Dagger","Great Knife","1090000"],
  ["Dagger","Bloodstained Dagger","1140000"],
  ["Dagger","Erdsteel Dagger","1150000"],
  ["Dagger","Fire Knight's Shortsword","1510000"],
  ["Dagger","Wakizashi","1100000"],
  ["Dagger","Main-gauche","1500000"],
  ["Dagger","Celebrant's Sickle","1060000"],
  ["Dagger","Ivory Sickle","1130000"],
  ["Dagger","Crystal Knife","1050000"],
  ["Dagger","Scorpion's Stinger","1080000"],
  ["Dagger","Cinquedea","1110000"],
  ["Dagger","Glintstone Kris","1070000"],
  ["Dagger","Reduvia","1040000"],
  ["Dagger","Blade of Calling","1160000"],
  ["Dagger","Black Knife","1010000"],
  ["Throwing Blade","Smithscript Dagger","63500000"],
  ["Straight Sword","Short Sword","2010000"],
  ["Straight Sword","Longsword","2000000"],
  ["Straight Sword","Broadsword","2020000"],
  ["Straight Sword","Weathered Straight Sword","2050000"],
  ["Straight Sword","Lordsworn's Straight Sword","2040000"],
  ["Straight Sword","Noble's Slender Sword","2230000"],
  ["Straight Sword","Cane Sword","2210000"],
  ["Straight Sword","Stone-Sheathed Sword","2540000"],
  ["Straight Sword","Warhawk's Talon","2240000"],
  ["Straight Sword","Lazuli Glintstone Sword","2250000"],
  ["Straight Sword","Carian Knight's Sword","2180000"],
  ["Straight Sword","Crystal Sword","2150000"],
  ["Straight Sword","Rotten Crystal Sword","2260000"],
  ["Straight Sword","Miquellan Knight's Sword","2200000"],
  ["Straight Sword","Ornamental Straight Sword","2060000"],
  ["Straight Sword","Golden Epitaph","2070000"],
  ["Straight Sword","Sword of St. Trina","2190000"],
  ["Straight Sword","Velvet Sword of St. Trina","2510000"],
  ["Straight Sword","Regalia of Eochaid","2220000"],
  ["Straight Sword","Coded Sword","2110000"],
  ["Straight Sword","Sword of Night and Flame","2140000"],
  ["Straight Sword","Sword of Light","2550000"],
  ["Straight Sword","Sword of Darkness","2560000"],
  ["Light Greatsword","Milady","67500000"],
  ["Light Greatsword","Leda's Sword","67510000"],
  ["Light Greatsword","Rellana's Twin Blades","67520000"],
  ["Greatsword","Bastard Sword","3000000"],
  ["Greatsword","Claymore","3180000"],
  ["Greatsword","Iron Greatsword","3020000"],
  ["Greatsword","Lordsworn's Greatsword","3030000"],
  ["Greatsword","Knight's Greatsword","3040000"],
  ["Greatsword","Banished Knight's Greatsword","3080000"],
  ["Greatsword","Forked Greatsword","3010000"],
  ["Greatsword","Lizard Greatsword","3520000"],
  ["Greatsword","Flamberge","3050000"],
  ["Greatsword","Gargoyle's Greatsword","3190000"],
  ["Greatsword","Gargoyle's Blackblade","3210000"],
  ["Greatsword","Inseparable Sword","2090000"],
  ["Greatsword","Sword of Milos","3160000"],
  ["Greatsword","Marais Executioner's Sword","3150000"],
  ["Greatsword","Greatsword of Solitude","3550000"],
  ["Greatsword","Ordovis's Greatsword","3060000"],
  ["Greatsword","Alabaster Lord's Sword","3070000"],
  ["Greatsword","Death's Poker","3200000"],
  ["Greatsword","Helphen's Steeple","3130000"],
  ["Greatsword","Blasphemous Blade","3140000"],
  ["Greatsword","Golden Order Greatsword","3170000"],
  ["Greatsword","Dark Moon Greatsword","3090000"],
  ["Greatsword","Greatsword of Damnation","3510000"],
  ["Greatsword","Sacred Relic Sword","3100000"],
  ["Colossal Sword","Zweihander","4040000"],
  ["Colossal Sword","Greatsword","4000000"],
  ["Colossal Sword","Watchdog's Greatsword","4010000"],
  ["Colossal Sword","Fire Knight's Greatsword","4520000"],
  ["Colossal Sword","Troll's Golden Sword","4030000"],
  ["Colossal Sword","Troll Knight's Sword","4110000"],
  ["Colossal Sword","Moonrithyll's Knight Sword","4540000"],
  ["Colossal Sword","Royal Greatsword","4060000"],
  ["Colossal Sword","Grafted Blade Greatsword","4100000"],
  ["Colossal Sword","Ruins Greatsword","4080000"],
  ["Colossal Sword","Ancient Meteoric Ore Greatsword","4500000"],
  ["Colossal Sword","Starscourge Greatsword","4050000"],
  ["Colossal Sword","Greatsword of Radahn (Lord)","4530000"],
  ["Colossal Sword","Greatsword of Radahn (Light)","4550000"],
  ["Colossal Sword","Godslayer's Greatsword","4070000"],
  ["Colossal Sword","Maliketh's Black Blade","4020000"],
  ["Thrusting Sword","Rapier","5020000"],
  ["Thrusting Sword","Estoc","5000000"],
  ["Thrusting Sword","Noble's Estoc","5060000"],
  ["Thrusting Sword","Cleanrot Knight's Sword","5010000"],
  ["Thrusting Sword","Rogier's Rapier","5030000"],
  ["Thrusting Sword","Antspur Rapier","5040000"],
  ["Thrusting Sword","Frozen Needle","5050000"],
  ["Thrusting Sword","Carian Sorcery Sword","2530000"],
  ["Heavy Thrusting Sword","Great Épée","6020000"],
  ["Heavy Thrusting Sword","Godskin Stitcher","6010000"],
  ["Heavy Thrusting Sword","Queelign's Greatsword","6500000"],
  ["Heavy Thrusting Sword","Bloody Helice","6000000"],
  ["Heavy Thrusting Sword","Dragon King's Cragblade","6040000"],
  ["Heavy Thrusting Sword","Sword Lance","3500000"],
  ["Curved Sword","Scimitar","7140000"],
  ["Curved Sword","Falchion","7000000"],
  ["Curved Sword","Shamshir","7030000"],
  ["Curved Sword","Grossmesser","7150000"],
  ["Curved Sword","Bandit's Curved Sword","7040000"],
  ["Curved Sword","Shotel","7020000"],
  ["Curved Sword","Scavenger's Curved Sword","7080000"],
  ["Curved Sword","Mantis Blade","7120000"],
  ["Curved Sword","Beastman's Curved Sword","7010000"],
  ["Curved Sword","Flowing Curved Sword","7060000"],
  ["Curved Sword","Serpent-God's Curved Sword","7110000"],
  ["Curved Sword","Magma Blade","7050000"],
  ["Curved Sword","Spirit Sword","7500000"],
  ["Curved Sword","Nox Flowing Sword","2080000"],
  ["Curved Sword","Wing of Astel","7070000"],
  ["Curved Sword","Falx","7510000"],
  ["Curved Sword","Dancing Blade of Ranah","7520000"],
  ["Curved Sword","Horned Warrior's Sword","7530000"],
  ["Curved Sword","Eclipse Shotel","7100000"],
  ["Curved Greatsword","Dismounter","8020000"],
  ["Curved Greatsword","Omen Cleaver","8060000"],
  ["Curved Greatsword","Monk's Flameblade","8070000"],
  ["Curved Greatsword","Beastman's Cleaver","8080000"],
  ["Curved Greatsword","Freyja's Greatsword","8510000"],
  ["Curved Greatsword","Bloodhound's Fang","8030000"],
  ["Curved Greatsword","Onyx Lord's Greatsword","8010000"],
  ["Curved Greatsword","Zamor Curved Sword","8050000"],
  ["Curved Greatsword","Magma Wyrm's Scalesword","8040000"],
  ["Curved Greatsword","Horned Warrior's Greatsword","8520000"],
  ["Curved Greatsword","Morgott's Cursed Sword","8100000"],
  ["Backhand Blade","Backhand Blade","64500000"],
  ["Backhand Blade","Smithscript Cirque","64510000"],
  ["Backhand Blade","Curseblade's Cirque","64520000"],
  ["Katana","Uchigatana","9000000"],
  ["Katana","Nagakiba","9010000"],
  ["Katana","Serpentbone Blade","9080000"],
  ["Katana","Meteoric Ore Blade","9030000"],
  ["Katana","Moonveil","9060000"],
  ["Katana","Sword of Night","9500000"],
  ["Katana","Rivers of Blood","9040000"],
  ["Katana","Dragonscale Blade","9070000"],
  ["Katana","Star-Lined Sword","2520000"],
  ["Katana","Hand of Malenia","9020000"],
  ["Great Katana","Great Katana","66500000"],
  ["Great Katana","Dragon-Hunter's Great Katana","66510000"],
  ["Great Katana","Rakshasa's Great Katana","66520000"],
  ["Twinblade","Twinblade","10000000"],
  ["Twinblade","Twinned Knight Swords","10030000"],
  ["Twinblade","Black Steel Twinblade","10510000"],
  ["Twinblade","Godskin Peeler","10010000"],
  ["Twinblade","Gargoyle's Twinblade","10080000"],
  ["Twinblade","Gargoyle's Black Blades","10090000"],
  ["Twinblade","Eleonora's Poleblade","10050000"],
  ["Twinblade","Euporia","10500000"],
  ["Axe","Hand Axe","14020000"],
  ["Axe","Forked Hatchet","14010000"],
  ["Axe","Forked-Tongue Hatchet","14540000"],
  ["Axe","Battle Axe","14000000"],
  ["Axe","Messmer Soldier's Axe","14520000"],
  ["Axe","Warped Axe","15010000"],
  ["Axe","Jawbone Axe","14030000"],
  ["Axe","Iron Cleaver","14040000"],
  ["Axe","Highland Axe","14100000"],
  ["Axe","Smithscript Axe","14500000"],
  ["Axe","Celebrant's Cleaver","14060000"],
  ["Axe","Sacrificial Axe","14110000"],
  ["Axe","Icerind Hatchet","14080000"],
  ["Axe","Ripple Blade","14050000"],
  ["Axe","Stormhawk Axe","14140000"],
  ["Axe","Rosus' Axe","14120000"],
  ["Axe","Death Knight's Twin Axes","14510000"],
  ["Greataxe","Greataxe","15000000"],
  ["Greataxe","Crescent Moon Axe","15030000"],
  ["Greataxe","Longhaft Axe","15050000"],
  ["Greataxe","Executioner's Greataxe","15080000"],
  ["Greataxe","Great Omenkiller Cleaver","15020000"],
  ["Greataxe","Rusted Anchor","15060000"],
  ["Greataxe","Butchering Knife","15120000"],
  ["Greataxe","Bonny Butchering Knife","15510000"],
  ["Greataxe","Gargoyle's Great Axe","15130000"],
  ["Greataxe","Gargoyle's Black Axe","15140000"],
  ["Greataxe","Death Knight's Longhaft Axe","15500000"],
  ["Greataxe","Winged Greathorn","15110000"],
  ["Greataxe","Axe of Godrick","15040000"],
  ["Greataxe","Putrescence Cleaver","8500000"],
  ["Hammer","Club","11010000"],
  ["Hammer","Curved Club","11030000"],
  ["Hammer","Spiked Club","11070000"],
  ["Hammer","Stone Club","11140000"],
  ["Hammer","Mace","11000000"],
  ["Hammer","Morning Star","11050000"],
  ["Hammer","Warpick","11040000"],
  ["Hammer","Hammer","11080000"],
  ["Hammer","Monk's Flamemace","11090000"],
  ["Hammer","Varré's Bouquet","11060000"],
  ["Hammer","Envoy's Horn","11100000"],
  ["Hammer","Nox Flowing Hammer","11120000"],
  ["Hammer","Ringed Finger","11130000"],
  ["Hammer","Scepter of the All-Knowing","11110000"],
  ["Hammer","Flowerstone Gavel","11500000"],
  ["Hammer","Marika's Hammer","11150000"],
  ["Flail","Flail","13010000"],
  ["Flail","Nightrider Flail","13000000"],
  ["Flail","Chainlink Flail","13040000"],
  ["Flail","Family Heads","13020000"],
  ["Flail","Serpent Flail","13500000"],
  ["Flail","Bastard's Stars","13030000"],
  ["Great Hammer","Large Club","12000000"],
  ["Great Hammer","Curved Great Club","12080000"],
  ["Great Hammer","Great Mace","12060000"],
  ["Great Hammer","Pickaxe","12140000"],
  ["Great Hammer","Brick Hammer","12190000"],
  ["Great Hammer","Battle Hammer","12020000"],
  ["Great Hammer","Rotten Battle Hammer","12210000"],
  ["Great Hammer","Celebrant's Skull","12130000"],
  ["Great Hammer","Great Stars","12180000"],
  ["Great Hammer","Black Steel Greathammer","12520000"],
  ["Great Hammer","Smithscript Greathammer","12500000"],
  ["Great Hammer","Greathorn Hammer","12010000"],
  ["Great Hammer","Envoy's Long Horn","12160000"],
  ["Great Hammer","Cranial Vessel Candlestand","12170000"],
  ["Great Hammer","Beastclaw Greathammer","12150000"],
  ["Great Hammer","Devourer's Scepter","12200000"],
  ["Colossal Weapon","Duelist Greataxe","23040000"],
  ["Colossal Weapon","Rotten Greataxe","23150000"],
  ["Colossal Weapon","Golem's Halberd","23120000"],
  ["Colossal Weapon","Giant-Crusher","23110000"],
  ["Colossal Weapon","Prelate's Inferno Crozier","23000000"],
  ["Colossal Weapon","Great Club","23020000"],
  ["Colossal Weapon","Troll's Hammer","23130000"],
  ["Colossal Weapon","Dragon Greatclaw","23060000"],
  ["Colossal Weapon","Bloodfiend's Arm","12530000"],
  ["Colossal Weapon","Watchdog's Staff","23010000"],
  ["Colossal Weapon","Staff of the Avatar","23070000"],
  ["Colossal Weapon","Rotten Staff","23140000"],
  ["Colossal Weapon","Envoy's Greathorn","23030000"],
  ["Colossal Weapon","Ghiza's Wheel","23100000"],
  ["Colossal Weapon","Fallingstar Beast Jaw","23080000"],
  ["Colossal Weapon","Anvil Hammer","12510000"],
  ["Colossal Weapon","Devonia's Hammer","23500000"],
  ["Colossal Weapon","Axe of Godfrey","23050000"],
  ["Colossal Weapon","Shadow Sunflower Blossom","23510000"],
  ["Colossal Weapon","Gazing Finger","23520000"],
  ["Spear","Short Spear","16000000"],
  ["Spear","Iron Spear","16150000"],
  ["Spear","Spear","16010000"],
  ["Spear","Partisan","16050000"],
  ["Spear","Pike","16070000"],
  ["Spear","Swift Spear","16520000"],
  ["Spear","Spiked Spear","16140000"],
  ["Spear","Cross-Naginata","16110000"],
  ["Spear","Clayman's Harpoon","16030000"],
  ["Spear","Bloodfiend's Fork","16540000"],
  ["Spear","Celebrant's Rib-Rake","16060000"],
  ["Spear","Torchpole","16080000"],
  ["Spear","Smithscript Spear","16500000"],
  ["Spear","Inquisitor's Girandole","16130000"],
  ["Spear","Crystal Spear","16020000"],
  ["Spear","Rotten Crystal Spear","16160000"],
  ["Spear","Cleanrot Spear","16040000"],
  ["Spear","Death Ritual Spear","16120000"],
  ["Spear","Bolt of Gransax","16090000"],
  ["Great Spear","Lance","17060000"],
  ["Great Spear","Messmer Soldier's Spear","17510000"],
  ["Great Spear","Treespear","17070000"],
  ["Great Spear","Serpent-Hunter","17030000"],
  ["Great Spear","Siluria's Tree","17020000"],
  ["Great Spear","Vyke's War Spear","17050000"],
  ["Great Spear","Barbed Staff-Spear","17520000"],
  ["Great Spear","Bloodfiend's Sacred Spear","16550000"],
  ["Great Spear","Mohgwyn's Sacred Spear","17010000"],
  ["Great Spear","Spear of the Impaler","17500000"],
  ["Halberd","Halberd","18000000"],
  ["Halberd","Banished Knight's Halberd","18030000"],
  ["Halberd","Lucerne","18020000"],
  ["Halberd","Glaive","18090000"],
  ["Halberd","Vulgar Militia Shotel","18130000"],
  ["Halberd","Vulgar Militia Saw","18070000"],
  ["Halberd","Guardian's Swordspear","18110000"],
  ["Halberd","Gargoyle's Halberd","18150000"],
  ["Halberd","Gargoyle's Black Halberd","18160000"],
  ["Halberd","Nightrider Glaive","18050000"],
  ["Halberd","Pest's Glaive","18010000"],
  ["Halberd","Ripple Crescent Halberd","18060000"],
  ["Halberd","Golden Halberd","18080000"],
  ["Halberd","Dragon Halberd","18140000"],
  ["Halberd","Loretta's War Sickle","18100000"],
  ["Halberd","Commander's Standard","18040000"],
  ["Halberd","Spirit Glaive","18500000"],
  ["Halberd","Poleblade of the Bud","18510000"],
  ["Reaper","Scythe","19000000"],
  ["Reaper","Grave Scythe","19010000"],
  ["Reaper","Halo Scythe","19020000"],
  ["Reaper","Winged Scythe","19060000"],
  ["Reaper","Obsidian Lamina","19500000"],
  ["Whip","Whip","20000000"],
  ["Whip","Thorned Whip","20020000"],
  ["Whip","Urumi","20070000"],
  ["Whip","Hoslow's Petal Whip","20050000"],
  ["Whip","Tooth Whip","20500000"],
  ["Whip","Magma Whip Candlestick","20030000"],
  ["Whip","Giant's Red Braid","20060000"],
  ["Fist","Unarmed","110000"],
  ["Fist","Caestus","21000000"],
  ["Fist","Spiked Caestus","21010000"],
  ["Fist","Katar","21100000"],
  ["Fist","Pata","21510000"],
  ["Fist","Iron Ball","21070000"],
  ["Fist","Star Fist","21080000"],
  ["Fist","Clinging Bone","21110000"],
  ["Fist","Veteran's Prosthesis","21120000"],
  ["Fist","Cipher Pata","21130000"],
  ["Fist","Poisoned Hand","21520000"],
  ["Fist","Madding Hand","21530000"],
  ["Fist","Thiollier's Hidden Needle","21500000"],
  ["Fist","Golem Fist","21540000"],
  ["Fist","Grafted Dragon","21060000"],
  ["Hand-to-Hand","Dryleaf Arts","60500000"],
  ["Hand-to-Hand","Dane's Footwork","60510000"],
  ["Claw","Hookclaws","22000000"],
  ["Claw","Bloodhound Claws","22020000"],
  ["Claw","Venomous Fang","22010000"],
  ["Claw","Raptor Talons","22030000"],
  ["Claw","Claws of Night","22500000"],
  ["Beast Claw","Beast Claw","68500000"],
  ["Beast Claw","Red Bear's Claw","68510000"],
  ["Perfume Bottle","Firespark Perfume Bottle","61500000"],
  ["Perfume Bottle","Lightning Perfume Bottle","61530000"],
  ["Perfume Bottle","Chilling Perfume Bottle","61510000"],
  ["Perfume Bottle","Frenzyflame Perfume Bottle","61520000"],
  ["Perfume Bottle","Deadly Poison Perfume Bottle","61540000"],
  ["Light Bow","Shortbow","40000000"],
  ["Light Bow","Composite Bow","40050000"],
  ["Light Bow","Red Branch Shortbow","40020000"],
  ["Light Bow","Misbegotten Shortbow","40010000"],
  ["Light Bow","Harp Bow","40030000"],
  ["Light Bow","Bone Bow","40500000"],
  ["Bow","Longbow","41000000"],
  ["Bow","Albinauric Bow","41010000"],
  ["Bow","Black Bow","41070000"],
  ["Bow","Ansbach's Longbow","41510000"],
  ["Bow","Pulley Bow","41060000"],
  ["Bow","Horn Bow","41020000"],
  ["Bow","Serpent Bow","41040000"],
  ["Bow","Erdtree Bow","41030000"],
  ["Greatbow","Greatbow","42040000"],
  ["Greatbow","Golem Greatbow","42010000"],
  ["Greatbow","Erdtree Greatbow","42030000"],
  ["Greatbow","Igon's Greatbow","42500000"],
  ["Greatbow","Lion Greatbow","42000000"],
  ["Crossbow","Soldier's Crossbow","43000000"],
  ["Crossbow","Light Crossbow","43020000"],
  ["Crossbow","Heavy Crossbow","43030000"],
  ["Crossbow","Arbalest","43080000"],
  ["Crossbow","Crepus's Black-Key Crossbow","43110000"],
  ["Crossbow","Pulley Crossbow","43050000"],
  ["Crossbow","Repeating Crossbow","43500000"],
  ["Crossbow","Spread Crossbow","43510000"],
  ["Crossbow","Full Moon Crossbow","43060000"],
  ["Ballista","Hand Ballista","44000000"],
  ["Ballista","Jar Cannon","44010000"],
  ["Ballista","Rabbath's Cannon","44500000"],
  ["Glintstone Staff","Astrologer's Staff","33130000"],
  ["Glintstone Staff","Glintstone Staff","33000000"],
  ["Glintstone Staff","Academy Glintstone Staff","33200000"],
  ["Glintstone Staff","Digger's Staff","33120000"],
  ["Glintstone Staff","Demi-Human Queen's Staff","33060000"],
  ["Glintstone Staff","Azur's Glintstone Staff","33230000"],
  ["Glintstone Staff","Lusat's Glintstone Staff","33240000"],
  ["Glintstone Staff","Carian Glintstone Staff","33210000"],
  ["Glintstone Staff","Carian Glintblade Staff","33170000"],
  ["Glintstone Staff","Carian Regal Scepter","33090000"],
  ["Glintstone Staff","Albinauric Staff","33190000"],
  ["Glintstone Staff","Staff of Loss","33280000"],
  ["Glintstone Staff","Gelmir Glintstone Staff","33050000"],
  ["Glintstone Staff","Crystal Staff","33040000"],
  ["Glintstone Staff","Rotten Crystal Staff","33270000"],
  ["Glintstone Staff","Meteorite Staff","33250000"],
  ["Glintstone Staff","Staff of the Guilty","33260000"],
  ["Glintstone Staff","Prince of Death's Staff","33180000"],
  ["Glintstone Staff","Maternal Staff","33520000"],
  ["Glintstone Staff","Staff of the Great Beyond","33510000"],
  ["Sacred Seal","Finger Seal","34000000"],
  ["Sacred Seal","Erdtree Seal","34070000"],
  ["Sacred Seal","Golden Order Seal","34060000"],
  ["Sacred Seal","Dryleaf Seal","34500000"],
  ["Sacred Seal","Fire Knight's Seal","34510000"],
  ["Sacred Seal","Spiraltree Seal","34520000"],
  ["Sacred Seal","Gravel Stone Seal","34030000"],
  ["Sacred Seal","Giant's Seal","34020000"],
  ["Sacred Seal","Godslayer's Seal","34010000"],
  ["Sacred Seal","Clawmark Seal","34040000"],
  ["Sacred Seal","Frenzied Flame Seal","34090000"],
  ["Sacred Seal","Dragon Communion Seal","34080000"],
  ["Torch","Torch","24000000"],
  ["Torch","Beast-Repellent Torch","24060000"],
  ["Torch","Steel-Wire Torch","24020000"],
  ["Torch","Sentry's Torch","24070000"],
  ["Torch","Ghostflame Torch","24050000"],
  ["Torch","St. Trina's Torch","24040000"],
  ["Torch","Nanaya's Torch","24500000"],
  ["Torch","Lamenting Visage","24510000"],
  ["Small Shield","Rickety Shield","30030000"],
  ["Small Shield","Riveted Wooden Shield","30090000"],
  ["Small Shield","Blue-White Wooden Shield","30100000"],
  ["Small Shield","Scripture Wooden Shield","30080000"],
  ["Small Shield","Red Thorn Roundshield","30070000"],
  ["Small Shield","Pillory Shield","30040000"],
  ["Small Shield","Buckler","30000000"],
  ["Small Shield","Iron Roundshield","30120000"],
  ["Small Shield","Gilded Iron Shield","30130000"],
  ["Small Shield","Man-Serpent's Shield","30020000"],
  ["Small Shield","Ice Crest Shield","30140000"],
  ["Small Shield","Rift Shield","30110000"],
  ["Small Shield","Perfumer's Shield","30010000"],
  ["Small Shield","Shield of the Guilty","31170000"],
  ["Small Shield","Spiralhorn Shield","30190000"],
  ["Small Shield","Smoldering Shield","30150000"],
  ["Small Shield","Coil Shield","30200000"],
  ["Small Shield","Smithscript Shield","30510000"],
  ["Small Shield","Shield of Night","21550000"],
  ["Medium Shield","Hawk Crest Wooden Shield","31270000"],
  ["Medium Shield","Horse Crest Wooden Shield","31240000"],
  ["Medium Shield","Candletree Wooden Shield","31250000"],
  ["Medium Shield","Flame Crest Wooden Shield","31260000"],
  ["Medium Shield","Marred Wooden Shield","31020000"],
  ["Medium Shield","Sun Realm Shield","31050000"],
  ["Medium Shield","Round Shield","31070000"],
  ["Medium Shield","Large Leather Shield","31230000"],
  ["Medium Shield","Black Leather Shield","31340000"],
  ["Medium Shield","Marred Leather Shield","31010000"],
  ["Medium Shield","Heater Shield","31330000"],
  ["Medium Shield","Blue Crest Heater Shield","31300000"],
  ["Medium Shield","Red Crest Heater Shield","31290000"],
  ["Medium Shield","Beast Crest Heater Shield","31280000"],
  ["Medium Shield","Inverted Hawk Heater Shield","31320000"],
  ["Medium Shield","Eclipse Crest Heater Shield","31310000"],
  ["Medium Shield","Kite Shield","31000000"],
  ["Medium Shield","Blue-Gold Kite Shield","31100000"],
  ["Medium Shield","Scorpion Kite Shield","31080000"],
  ["Medium Shield","Twinbird Kite Shield","31090000"],
  ["Medium Shield","Brass Shield","31130000"],
  ["Medium Shield","Messmer Soldier Shield","31500000"],
  ["Medium Shield","Banished Knight's Shield","31030000"],
  ["Medium Shield","Wolf Crest Shield","31510000"],
  ["Medium Shield","Serpent Crest Shield","31520000"],
  ["Medium Shield","Albinauric Shield","31040000"],
  ["Medium Shield","Beastman's Jar-Shield","30060000"],
  ["Medium Shield","Carian Knight's Shield","31190000"],
  ["Medium Shield","Silver Mirrorshield","31060000"],
  ["Medium Shield","Great Turtle Shell","31140000"],
  ["Medium Shield","Golden Lion Shield","31530000"],
  ["Greatshield","Wooden Greatshield","32290000"],
  ["Greatshield","Lordsworn's Shield","32300000"],
  ["Greatshield","Briar Greatshield","32050000"],
  ["Greatshield","Spiked Palisade Shield","32170000"],
  ["Greatshield","Icon Shield","32140000"],
  ["Greatshield","Golden Beast Crest Shield","32090000"],
  ["Greatshield","Manor Towershield","32190000"],
  ["Greatshield","Crossed-Tree Towershield","32200000"],
  ["Greatshield","Inverted Hawk Towershield","32210000"],
  ["Greatshield","Dragon Towershield","32000000"],
  ["Greatshield","Distinguished Greatshield","32020000"],
  ["Greatshield","Gilded Greatshield","32270000"],
  ["Greatshield","Cuckoo Greatshield","32250000"],
  ["Greatshield","Redmane Greatshield","32230000"],
  ["Greatshield","Golden Greatshield","32260000"],
  ["Greatshield","Haligtree Crest Greatshield","32280000"],
  ["Greatshield","Black Steel Greatshield","32500000"],
  ["Greatshield","Crucible Hornshield","32030000"],
  ["Greatshield","Dragonclaw Shield","32040000"],
  ["Greatshield","Fingerprint Stone Shield","32130000"],
  ["Greatshield","Eclipse Crest Greatshield","32240000"],
  ["Greatshield","Ant's Skull Plate","32220000"],
  ["Greatshield","Erdtree Greatshield","32080000"],
  ["Greatshield","Jellyfish Shield","32120000"],
  ["Greatshield","Visage Shield","32160000"],
  ["Greatshield","One-Eyed Shield","32150000"],
  ["Greatshield","Verdigris Greatshield","32520000"],
  ["Thrusting Shield","Dueling Shield","62500000"],
  ["Thrusting Shield","Carian Thrusting Shield","62510000"],
];

// Weapon class to canMountWep column mapping
const classToColumnMap = {
  "Dagger": "canMountWep_Dagger",
  "Straight Sword": "canMountWep_SwordNormal",
  "Greatsword": "canMountWep_SwordLarge",
  "Colossal Sword": "canMountWep_SwordGigantic",
  "Curved Sword": "canMountWep_SaberNormal",
  "Curved Greatsword": "canMountWep_SaberLarge",
  "Katana": "canMountWep_katana",
  "Twinblade": "canMountWep_SwordDoubleEdge",
  "Thrusting Sword": "canMountWep_SwordPierce",
  "Heavy Thrusting Sword": "canMountWep_RapierHeavy",
  "Axe": "canMountWep_AxeNormal",
  "Greataxe": "canMountWep_AxeLarge",
  "Hammer": "canMountWep_HammerNormal",
  "Great Hammer": "canMountWep_HammerLarge",
  "Flail": "canMountWep_Flail",
  "Spear": "canMountWep_SpearNormal",
  "Great Spear": "canMountWep_SpearHeavy",
  "Halberd": "canMountWep_SpearAxe",
  "Reaper": "canMountWep_Sickle",
  "Fist": "canMountWep_Knuckle",
  "Claw": "canMountWep_Claw",
  "Whip": "canMountWep_Whip",
  "Colossal Weapon": "canMountWep_AxhammerLarge",
  "Light Bow": "canMountWep_BowSmall",
  "Bow": "canMountWep_BowNormal",
  "Greatbow": "canMountWep_BowLarge",
  "Crossbow": "canMountWep_ClossBow",
  "Ballista": "canMountWep_Ballista",
  "Glintstone Staff": "canMountWep_Staff",
  "Sacred Seal": "canMountWep_Talisman",
  "Small Shield": "canMountWep_ShieldSmall",
  "Medium Shield": "canMountWep_ShieldNormal",
  "Greatshield": "canMountWep_ShieldLarge",
  "Torch": "canMountWep_Torch",
  "Hand-to-Hand": "canMountWep_HandToHand",
  "Perfume Bottle": "canMountWep_PerfumeBottle",
  "Thrusting Shield": "canMountWep_ThrustingShield",
  "Throwing Blade": "canMountWep_ThrowingWeapon",
  "Backhand Blade": "canMountWep_ReverseHandSword",
  "Light Greatsword": "canMountWep_LightGreatsword",
  "Great Katana": "canMountWep_GreatKatana",
  "Beast Claw": "canMountWep_BeastClaw",
};

// Affinity index to name mapping
const affinityMap = {
  0: "Standard",
  1: "Heavy",
  2: "Keen",
  3: "Quality",
  4: "Fire",
  5: "Flame Art",
  6: "Lightning",
  7: "Sacred",
  8: "Magic",
  9: "Cold",
  10: "Poison",
  11: "Blood",
  12: "Occult",
};

// Headers from EquipParamGem
const headers = ["ID","Name","sortGroupId","swordArtsParamId","sortId","configurableWepAttr00","configurableWepAttr01","configurableWepAttr02","configurableWepAttr03","configurableWepAttr04","configurableWepAttr05","configurableWepAttr06","configurableWepAttr07","configurableWepAttr08","configurableWepAttr09","configurableWepAttr10","configurableWepAttr11","configurableWepAttr12","defaultWepAttr","isSpecialSwordArt","canMountWep_Dagger","canMountWep_SwordNormal","canMountWep_SwordLarge","canMountWep_SwordGigantic","canMountWep_SaberNormal","canMountWep_SaberLarge","canMountWep_katana","canMountWep_SwordDoubleEdge","canMountWep_SwordPierce","canMountWep_RapierHeavy","canMountWep_AxeNormal","canMountWep_AxeLarge","canMountWep_HammerNormal","canMountWep_HammerLarge","canMountWep_Flail","canMountWep_SpearNormal","canMountWep_SpearLarge","canMountWep_SpearHeavy","canMountWep_SpearAxe","canMountWep_Sickle","canMountWep_Knuckle","canMountWep_Claw","canMountWep_Whip","canMountWep_AxhammerLarge","canMountWep_BowSmall","canMountWep_BowNormal","canMountWep_BowLarge","canMountWep_ClossBow","canMountWep_Ballista","canMountWep_Staff","canMountWep_Sorcery","canMountWep_Talisman","canMountWep_ShieldSmall","canMountWep_ShieldNormal","canMountWep_ShieldLarge","canMountWep_Torch","canMountWep_HandToHand","canMountWep_PerfumeBottle","canMountWep_ThrustingShield","canMountWep_ThrowingWeapon","canMountWep_ReverseHandSword","canMountWep_LightGreatsword","canMountWep_GreatKatana","canMountWep_BeastClaw"];

// Build header index map
const headerIndex = {};
headers.forEach((h, i) => headerIndex[h] = i);

// AoW data (only rows starting with "Ash of War:")
const aowData = [
  ["10000","Ash of War: Lion's Claw","10","100","350030","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE"],
  ["10100","Ash of War: Impaling Thrust","20","101","351010","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["10200","Ash of War: Piercing Fang","20","102","351020","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE"],
  ["10300","Ash of War: Spinning Slash","20","103","351000","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE"],
  ["10500","Ash of War: Charge Forth","30","105","352010","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["10600","Ash of War: Stamp (Upward Cut)","10","106","350000","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE"],
  ["10700","Ash of War: Stamp (Sweep)","10","107","350010","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE"],
  ["10800","Ash of War: Blood Tax","90","108","359020","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","11","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["10900","Ash of War: Repeating Thrust","20","109","351030","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["11000","Ash of War: Wild Strikes","10","110","350020","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE"],
  ["11100","Ash of War: Spinning Strikes","30","111","352020","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["11200","Ash of War: Double Slash","20","112","351040","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["11300","Ash of War: Prelate's Charge","50","113","355000","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","5","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["11400","Ash of War: Unsheathe","20","114","351060","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["11500","Ash of War: Square Off","30","115","352000","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["11600","Ash of War: Giant Hunt","30","116","352030","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE"],
  ["11800","Ash of War: Loretta's Slash","40","118","353060","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","8","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["11900","Ash of War: Poison Moth Flight","90","119","358010","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","10","FALSE","TRUE","TRUE","FALSE","FALSE","TRUE","FALSE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE"],
  ["12000","Ash of War: Spinning Weapon","40","120","353050","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","8","FALSE","TRUE","TRUE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE","TRUE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE"],
  ["12200","Ash of War: Storm Assault","30","122","352050","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["12300","Ash of War: Stormcaller","30","123","352060","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","FALSE","FALSE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE"],
  ["12400","Ash of War: Sword Dance","20","124","351050","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE"],
  ["20000","Ash of War: Glintblade Phalanx","40","200","353020","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","8","FALSE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["20100","Ash of War: Sacred Blade","80","201","357000","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","7","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE"],
  ["20200","Ash of War: Ice Spear","90","202","360000","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","9","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["20300","Ash of War: Glintstone Pebble","40","203","353010","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","8","FALSE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["20400","Ash of War: Bloody Slash","90","204","359010","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","11","FALSE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["20500","Ash of War: Lifesteal Fist","120","205","361010","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","12","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE"],
  ["20700","Ash of War: Eruption","50","207","354020","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","4","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE"],
  ["20800","Ash of War: Prayerful Strike","80","208","357010","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","7","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["20900","Ash of War: Gravitas","40","209","353070","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","8","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE"],
  ["21000","Ash of War: Storm Blade","30","210","352040","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","FALSE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["21200","Ash of War: Earthshaker","10","212","350080","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["21300","Ash of War: Golden Land","80","213","357050","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","7","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["21400","Ash of War: Flaming Strike","50","214","354000","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","4","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE"],
  ["21600","Ash of War: Thunderbolt","50","216","356000","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","6","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["21700","Ash of War: Lightning Slash","50","217","356010","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","6","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE"],
  ["21800","Ash of War: Carian Grandeur","40","218","353040","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","8","FALSE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["21900","Ash of War: Carian Greatsword","40","219","353030","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","8","FALSE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["22000","Ash of War: Vacuum Slice","30","220","352080","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["22100","Ash of War: Black Flame Tornado","50","221","355010","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","5","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["22200","Ash of War: Sacred Ring of Light","80","222","357020","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","7","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["22400","Ash of War: Blood Blade","90","224","359000","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","11","FALSE","TRUE","TRUE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE"],
  ["22500","Ash of War: Phantom Slash","30","225","352090","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["22600","Ash of War: Spectral Lance","120","226","361000","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","12","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["22700","Ash of War: Chilling Mist","90","227","360010","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","9","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE"],
  ["22800","Ash of War: Poisonous Mist","90","228","358000","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","10","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE"],
  ["30000","Ash of War: Shield Bash","140","300","363030","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["30100","Ash of War: Barricade Shield","140","301","363050","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["30200","Ash of War: Parry","140","302","363000","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","0","FALSE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE"],
  ["30500","Ash of War: Carian Retaliation","140","305","363070","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","8","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["30600","Ash of War: Storm Wall","140","306","363020","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["30700","Ash of War: Golden Parry","140","307","363010","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","7","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["30800","Ash of War: Shield Crash","140","308","363040","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["30900","Ash of War: No Skill","140","10","363080","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["31000","Ash of War: Thops's Barrier","140","309","363060","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","8","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["40000","Ash of War: Through and Through","130","400","362010","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["40100","Ash of War: Barrage","130","401","362020","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["40200","Ash of War: Mighty Shot","130","402","362000","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["40400","Ash of War: Enchanted Shot","130","404","362040","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["40500","Ash of War: Sky Shot","130","405","362030","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["40600","Ash of War: Rain of Arrows","130","406","362050","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["50100","Ash of War: Hoarfrost Stomp","90","501","360020","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","9","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["50200","Ash of War: Storm Stomp","30","502","352070","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["50300","Ash of War: Kick","10","503","350050","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["50400","Ash of War: Lightning Ram","50","504","356020","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","6","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["50500","Ash of War: Flame of the Redmanes","50","505","354010","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","4","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["50600","Ash of War: Ground Slam","10","506","350070","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["50700","Ash of War: Golden Slam","80","507","357060","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","7","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["50800","Ash of War: Waves of Darkness","40","508","353070","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","8","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["50900","Ash of War: Hoarah Loux's Earthshaker","10","509","350090","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["60000","Ash of War: Determination","30","600","352100","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE"],
  ["60100","Ash of War: Royal Knight's Resolve","30","601","352110","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE"],
  ["60200","Ash of War: Assassin's Gambit","120","602","361030","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","12","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","FALSE","FALSE"],
  ["60300","Ash of War: Golden Vow","80","603","357070","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","7","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["60400","Ash of War: Sacred Order","80","604","357030","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","7","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE"],
  ["60500","Ash of War: Shared Order","80","605","357040","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","7","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE"],
  ["60600","Ash of War: Seppuku","90","606","359030","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","11","TRUE","FALSE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE"],
  ["60700","Ash of War: Cragblade","10","607","350040","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE"],
  ["65000","Ash of War: Barbaric Roar","10","650","350110","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE"],
  ["65100","Ash of War: War Cry","10","651","350100","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE"],
  ["65200","Ash of War: Beast's Roar","20","652","351100","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["65300","Ash of War: Troll's Roar","10","653","350130","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE"],
  ["65400","Ash of War: Braggart's Roar","10","654","350120","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE"],
  ["70000","Ash of War: Endure","10","700","350060","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["70100","Ash of War: Vow of the Indomitable","80","701","357080","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","7","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["70200","Ash of War: Holy Ground","80","702","357090","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","7","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["80000","Ash of War: Quickstep","20","800","351070","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["80100","Ash of War: Bloodhound's Step","20","801","351080","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["80200","Ash of War: Raptor of the Mists","20","802","351090","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["85000","Ash of War: White Shadow's Lure","120","850","361020","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","12","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["200000","Ash of War: Dryleaf Whirlwind","125","2000","361510","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["200100","Ash of War: Aspects of the Crucible: Wings","80","2001","357100","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","7","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["400000","Ash of War: Spinning Gravity Thrust","10","4000","350041","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE"],
  ["401000","Ash of War: Palm Blast","125","4010","361500","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["402000","Ash of War: Piercing Throw","20","4020","351140","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE"],
  ["403000","Ash of War: Scattershot Throw","20","4030","351150","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE"],
  ["404000","Ash of War: Wall of Sparks","125","4040","361511","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["405000","Ash of War: Rolling Sparks","125","4050","361520","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["406000","Ash of War: Raging Beast","20","4060","351130","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE"],
  ["407000","Ash of War: Savage Claws","20","4070","351120","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE"],
  ["409000","Ash of War: Blind Spot","20","4090","351011","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE"],
  ["410000","Ash of War: Swift Slash","20","4100","351012","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE"],
  ["411000","Ash of War: Overhead Stance","20","4110","351061","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","2","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE"],
  ["412000","Ash of War: Wing Stance","30","4120","352006","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","3","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE"],
  ["413000","Ash of War: Blinkbolt","50","4130","356011","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","6","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["414000","Ash of War: Flame Skewer","50","4140","355020","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","5","TRUE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE"],
  ["415000","Ash of War: Savage Lion's Claw","10","4150","350031","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","1","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE"],
  ["416000","Ash of War: Divine Beast Frost Stomp","90","4160","360030","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","9","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["417000","Ash of War: Flame Spear","50","4170","355030","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","5","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","TRUE","TRUE","FALSE"],
  ["418000","Ash of War: Carian Sovereignty","40","4180","353045","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","8","FALSE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE"],
  ["419000","Ash of War: Shriek of Sorrow","120","4190","361040","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","12","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["422000","Ash of War: Ghostflame Call","90","4220","360011","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","9","FALSE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","FALSE"],
  ["505000","Ash of War: The Poison Flower Blooms Twice","90","5050","358020","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","10","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE"],
  ["548000","Ash of War: Igon's Drake Hunt","130","4210","362015","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE"],
  ["800000","Ash of War: Shield Strike","140","8000","363075","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","TRUE","0","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","FALSE","TRUE","TRUE","TRUE","FALSE","FALSE","FALSE","TRUE","FALSE","FALSE","FALSE","FALSE","FALSE"],
];

// Filter weapons to only those with a valid weapon class mapping
const validWeapons = weaponsData.filter(w => classToColumnMap[w[0]]);
console.log(`Total weapons with valid class mapping: ${validWeapons.length}`);
console.log(`Total AoWs: ${aowData.length}`);

// Generate CSV
const csvRows = ['weapon_name,weapon_id,affinity,aow_name'];
let totalCombinations = 0;

for (const weapon of validWeapons) {
  const weaponClass = weapon[0];
  const weaponName = weapon[1];
  const weaponId = weapon[2];
  const canMountWepCol = classToColumnMap[weaponClass];
  const canMountWepIdx = headerIndex[canMountWepCol];

  if (canMountWepIdx === undefined) {
    console.warn(`No column index found for ${canMountWepCol}`);
    continue;
  }

  for (let affinityIdx = 0; affinityIdx <= 12; affinityIdx++) {
    const affinityName = affinityMap[affinityIdx];
    const configAttrIdx = headerIndex[`configurableWepAttr${String(affinityIdx).padStart(2, '0')}`];

    for (const aow of aowData) {
      const aowName = aow[1];
      const canMountWep = aow[canMountWepIdx];
      const supportsAffinity = aow[configAttrIdx];

      if (canMountWep === 'TRUE' && supportsAffinity === 'TRUE') {
        // Escape weapon name and AoW name for CSV (handle commas and quotes)
        const escapedWeaponName = weaponName.includes(',') || weaponName.includes('"')
          ? `"${weaponName.replace(/"/g, '""')}"`
          : weaponName;
        const escapedAowName = aowName.includes(',') || aowName.includes('"')
          ? `"${aowName.replace(/"/g, '""')}"`
          : aowName;

        csvRows.push(`${escapedWeaponName},${weaponId},${affinityName},${escapedAowName}`);
        totalCombinations++;
      }
    }
  }
}

console.log(`Total combinations: ${totalCombinations}`);

// Write to file
const outputPath = path.join(import.meta.dirname, '..', 'aow_compatibility.csv');
fs.writeFileSync(outputPath, csvRows.join('\n'));
console.log(`CSV written to: ${outputPath}`);
